{
    "branch": "master",
    "verifyConditions": {                                                                                                                             
        "path": "semantic-release-docker",
        "registryUrl": "docker.io"                                                                                                                    
    },             
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# Deepsea Tensorflow Record Utility Changelog"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md"
                ]
            }
        ],
        "semantic-release-docker",                                                                                                                    
        [                                                                                                                                             
            "@semantic-release/exec",                                                                                                                 
            {                                                                                                                                         
                "prepareCmd": "docker build --build-arg DOCKER_GID=`id -g` --build-arg DOCKER_UID=`id -u` -t mbari/deepsea-tfrecord ."
            }                                                                                                                                         
        ],                                                                                                                                            
    ],                                                                                                                                                
    "publish": [                                                                                                                                      
        {                                                                                                                                             
            "path": "semantic-release-docker",                                                                                                        
            "name": "mbari/deepsea-tfrecord"
         }                                                                                                                                             
    ] 
}    
