{
    "branch": "master",
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/exec",
        {
          "verifyConditionsCmd",
          {
            "cmd": "printf '#!/usr/bin/env python\\n__version__ = \"%s\"\\n' ${nextRelease.version} > src/main/__init__.py"
          }
        },
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# DeepSea Tensorflow Record Utility Changelog"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md"
                ]
            }
        ]
    ]                                                                                                                                                
}    
